// authentication
export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS_FROM_NEXIS_LTD";
export const AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED";
export const AUTHENTICATION_LOADING = "AUTHENTICATION_LOADING";
export const AUTHENTICATION_LOGOUT = "AUTHENTICATION_LOGOUT";

export const STORE_ATTENDANCE_IN_REDXUX = "STORE_ATTENDANCE_IN_REDXUX";
export const SELECTED_ID = "SELECTED_ATTENDEE_ID";
